-- Enrich tour descriptions for RAG quality improvement
-- Targets all tours with description < 200 characters

UPDATE tour SET Description = 'Khám phá thủ đô Bangkok sôi động với các cung điện, chùa chiền lộng lẫy như Wat Arun, Wat Pho và Grand Palace. Tiếp tục hành trình tới Pattaya – thành phố biển nổi tiếng với bãi tắm đẹp, các show giải trí đặc sắc, chợ đêm và trò chơi thể thao dưới nước. Tour phù hợp cho gia đình, nhóm bạn và cặp đôi yêu thích văn hóa và biển đảo Đông Nam Á.' WHERE TourID = 18;

UPDATE tour SET Description = 'Hành trình khám phá hai đất nước phát triển bậc nhất Đông Nam Á. Singapore hiện đại với Gardens by the Bay, Marina Bay Sands, Universal Studios và ẩm thực đường phố đa sắc tộc. Kuala Lumpur cổ kính với Tháp đôi Petronas biểu tượng, khu phố Bukit Bintang sầm uất, chùa Batu Caves độc đáo. Tour 5 ngày trọn vẹn, bao gồm vé máy bay, khách sạn 4 sao và xe đưa đón.' WHERE TourID = 19;

UPDATE tour SET Description = 'Chinh phục thủ đô công nghệ Nhật Bản với kiến trúc hiện đại pha trộn văn hóa truyền thống. Ghé thăm Shinjuku, Shibuya, Asakusa với chùa Senso-ji linh thiêng. Điểm nhấn đặc biệt là ngắm Núi Phú Sĩ (Mt. Fuji) – biểu tượng của Nhật Bản từ hồ Kawaguchiko. Thưởng thức ẩm thực Nhật chính thống: ramen, sushi, tempura, matcha. Tour phù hợp với người yêu thiên nhiên, văn hóa anime và ẩm thực Nhật Bản.' WHERE TourID = 20;

UPDATE tour SET Description = 'Trải nghiệm Hàn Quốc mộng mơ qua 3 điểm đến nổi bật: Seoul – thủ đô sầm uất với khu mua sắm Myeongdong, cung điện Gyeongbokgung, Namsan Tower. Đảo Nami – hòn đảo lãng mạn với hàng cây thẳng tắp và cảnh mùa thu rực rỡ, bối cảnh phim Winter Sonata. Everland – công viên giải trí lớn nhất Hàn Quốc với các trò chơi cảm giác mạnh, vườn hoa lễ hội. Phù hợp cho người yêu K-pop, K-drama và ẩm thực Hàn Quốc.' WHERE TourID = 21;

UPDATE tour SET Description = 'Khám phá sự hòa quyện giữa Đông và Tây tại Hong Kong và Ma Cao. Hong Kong – siêu đô thị châu Á với đỉnh The Peak nhìn ra toàn cảnh, phố cổ Hollywood Road, công viên Disneyland, mua sắm tại Causeway Bay và Mongkok. Ma Cao – Las Vegas của châu Á với các sòng bài đẳng cấp, tàn tích pháo đài St. Paul, cầu nối liền với Hong Kong. Tour 5 ngày khám phá ẩm thực, văn hóa và giải trí độc đáo.' WHERE TourID = 22;

UPDATE tour SET Description = 'Hành trình khám phá Đài Loan qua hai thành phố lớn. Đài Bắc – thủ đô với tháp Taipei 101 hùng vĩ, chợ đêm Shilin nổi tiếng, bảo tàng Cố Cung lưu giữ cổ vật quý hiếm, suối nước nóng Beitou. Cao Hùng – thành phố cảng năng động phía Nam với Trung tâm Nghệ thuật Quốc gia, cảng Liuhe Night Market sôi động và cầu Ánh Đèn lung linh. Phù hợp người yêu văn hóa Đông Á và ẩm thực Đài Loan.' WHERE TourID = 23;

UPDATE tour SET Description = 'Hành trình lãng mạn khám phá kinh đô ánh sáng Paris và cung điện Versailles xa hoa. Tham quan Tháp Eiffel biểu tượng nước Pháp, dạo bộ dọc bờ sông Seine, khám phá bảo tàng Louvre với tác phẩm Mona Lisa. Điểm nhấn là tham quan Cung điện Versailles – kiệt tác kiến trúc baroque với vườn hoa tuyệt mỹ và phòng Gương lộng lẫy. Thưởng thức ẩm thực Pháp: croissant, bánh mì, rượu vang và pho mát. Tour phù hợp cho cặp đôi và người yêu nghệ thuật, kiến trúc châu Âu.' WHERE TourID = 29;

UPDATE tour SET Description = 'Khám phá Vịnh Hạ Long – kỳ quan thiên nhiên thế giới với hơn 1900 đảo đá vôi nhô lên từ mặt biển xanh ngọc. Trải nghiệm ngủ đêm trên du thuyền sang trọng, chèo kayak khám phá hang Sửng Sốt và hang Luồn bí ẩn. Tham quan làng chài Cửa Vạn nổi trên mặt nước, tắm biển tại bãi Ti Tốp, ngắm hoàng hôn tuyệt đẹp. Thưởng thức hải sản tươi sống đặc trưng vùng biển Quảng Ninh. Tour du lịch trong nước được yêu thích nhất Việt Nam.' WHERE TourID = 30;

UPDATE tour SET Description = 'Chinh phục đỉnh Fansipan – nóc nhà Đông Dương cao 3143m tại Sa Pa, Lào Cai. Trekking qua rừng nguyên sinh, ngắm ruộng bậc thang hoàng hôn tại Mù Cang Chải. Khám phá bản làng dân tộc H''Mông, Dao Đỏ với văn hóa và trang phục truyền thống độc đáo. Trải nghiệm sương mù Sa Pa huyền ảo vào buổi sáng sớm, thưởng thức ẩm thực núi rừng Tây Bắc như thắng cố, cá suối nướng và rượu ngô. Tour lý tưởng cho người yêu leo núi, thiên nhiên và văn hóa dân tộc thiểu số.' WHERE TourID = 31;

UPDATE tour SET Description = 'Khám phá Ninh Bình – vịnh Hạ Long trên cạn với cảnh quan núi non sông nước hùng vĩ. Tham quan Tràng An – di sản thế giới UNESCO được công nhận năm 2014 với hệ thống hang động và sông nước độc đáo. Chèo thuyền qua Tam Cốc – Bích Động ngắm lúa chín vàng uốn lượn giữa núi đá. Thăm cố đô Hoa Lư – kinh đô đầu tiên của nhà nước phong kiến trung ương tập quyền Việt Nam. Leo núi Mua ngắm toàn cảnh đồng bằng và sông Ngô Đồng. Phù hợp cho gia đình và người yêu thiên nhiên lịch sử.' WHERE TourID = 40;

UPDATE tour SET Description = 'Khám phá Sydney – thành phố sôi động nhất Australia với Nhà hát Opera Sydney biểu tượng, Cầu Cảng Harbour Bridge hùng tráng, bãi biển Bondi nổi tiếng thế giới. Tham quan Dãy Núi Blue Mountains – di sản thế giới với vách đá Three Sisters huyền thoại, rừng bạch đàn tỏa màu xanh lam bí ẩn. Trải nghiệm ẩm thực Úc và cuộc sống đa văn hóa. Phù hợp cho người yêu thiên nhiên hoang dã và kiến trúc đô thị châu Đại Dương.' WHERE TourID = 42;

UPDATE tour SET Description = 'Khám phá Dubai – thành phố tương lai giữa sa mạc với tòa nhà Burj Khalifa cao nhất thế giới, trung tâm mua sắm Dubai Mall xa hoa, nhảy dù ngắm sa mạc từ trên cao và cưỡi lạc đà trải nghiệm văn hóa Bedouin. Tiếp tục hành trình đến Abu Dhabi – thủ đô UAE với Nhà thờ Hồi giáo Sheikh Zayed lộng lẫy, đường đua F1 Yas Marina Circuit, công viên giải trí Ferrari World. Tour sang trọng kết hợp văn hóa và hiện đại cho người yêu cuộc sống xa hoa.' WHERE TourID = 43;

UPDATE tour SET Description = 'Trải nghiệm Chợ nổi Cái Răng – nét văn hóa đặc trưng của vùng sông nước miền Tây Nam Bộ. Ngồi trên thuyền khám phá khu chợ sầm uất với hàng trăm ghe xuồng chở trái cây, hàng hóa đặc sản. Thưởng thức các món ăn dân dã miền Tây: bún cá, bánh tét, hủ tiếu và cháo lòng. Ngắm cảnh bình minh trên sông Hậu, tham quan vườn trái cây xum xuê và làng nghề truyền thống. Điểm đến văn hóa lý tưởng để hiểu hơn về cuộc sống người dân Nam Bộ.' WHERE TourID = 44;

UPDATE tour SET Description = 'Trải nghiệm đặc biệt tại nhà hát Colosseum – show diễn nghệ thuật đặc sắc kết hợp âm nhạc, vũ điệu và ánh sáng hiện đại tại trung tâm giải trí hàng đầu. Thưởng thức chương trình biểu diễn nghệ thuật đỉnh cao với dàn diễn viên chuyên nghiệp, hiệu ứng âm thanh và ánh sáng ấn tượng. Bữa tối VIP kết hợp xem show với thực đơn hải sản cao cấp và đồ uống premium. Phù hợp cho cặp đôi, nhóm bạn và gia đình yêu thích nghệ thuật biểu diễn.' WHERE TourID = 67;

UPDATE tour SET Description = 'Hành trình khám phá Đài Loan qua nhiều điểm đến hấp dẫn: Đèo Cao Mỹ với cảnh sắc thiên nhiên tuyệt đẹp nhìn ra đại dương xanh biếc. Đài Trung – thành phố văn hóa với kiến trúc Nhật Bản còn lưu giữ. Đài Bắc – thủ đô sầm uất với Taipei 101, chợ đêm Shilin. Thác nước Thập Phần lung linh trong rừng sâu, nơi thả đèn trời theo phong tục địa phương. Phố cổ Đại Đạo Thành lưu giữ nét kiến trúc hoài cổ. Khám phá văn hóa, ẩm thực và phong cảnh đa dạng của Đài Loan.' WHERE TourID = 69;

UPDATE tour SET Description = 'Hành trình khám phá miền Trung Việt Nam cao cấp 3 ngày 2 đêm. Huế – cố đô triều Nguyễn với Đại Nội, lăng tẩm các vua, sông Hương thơ mộng, chùa Thiên Mụ cổ kính và ẩm thực Huế tinh tế. Đà Nẵng – thành phố đáng sống với Cầu Rồng phun lửa, Bà Nà Hills huyền ảo, cầu Vàng nổi tiếng toàn cầu, bãi biển Mỹ Khê đẹp nhất châu Á. Nghỉ dưỡng tại resort 5 sao ven biển, thưởng thức hải sản tươi và ẩm thực đặc trưng địa phương.' WHERE TourID = 80;

UPDATE tour SET Description = 'Nghỉ dưỡng biển cao cấp tại Phú Quốc – hòn đảo ngọc của Việt Nam thuộc tỉnh Kiên Giang. Resort 4 sao ven biển với hồ bơi vô cực nhìn ra Vịnh Thái Lan, bãi biển Ông Lang và Bãi Sao trong xanh tuyệt đẹp. Tham quan Vinpearl Safari – vườn thú bán hoang dã đầu tiên tại Việt Nam, VinWonders Phú Quốc, nhà tù Phú Quốc lịch sử. Thưởng thức hải sản tươi sống: cua Huỳnh Đế, nhum biển, ghẹ. Ngắm hoàng hôn tuyệt mỹ tại Bãi Dài – một trong những bãi hoàng hôn đẹp nhất thế giới.' WHERE TourID = 81;

UPDATE tour SET Description = 'Trekking khám phá Sa Pa và chinh phục đỉnh Fansipan 3143m – đỉnh núi cao nhất Đông Dương bằng cáp treo hoặc đi bộ. Băng qua rừng nguyên sinh với hệ sinh thái đa dạng, ngắm thác nước bạc xanh và suối chảy róc rách. Khám phá bản Cát Cát, bản Sin Chải với văn hóa người H''Mông Hoa truyền thống. Ngắm ruộng bậc thang kỳ vĩ mùa lúa chín vàng. Trải nghiệm đêm chợ Sa Pa sôi động, mua đặc sản thổ cẩm và ẩm thực núi rừng Tây Bắc. Tour lý tưởng cho người yêu thiên nhiên và phiêu lưu khám phá.' WHERE TourID = 82;

UPDATE tour SET Description = 'Trải nghiệm sông nước miền Tây đích thực tại Cần Thơ và Châu Đốc trong 2 ngày 1 đêm. Sáng sớm ra chợ nổi Cái Răng – nét văn hóa độc đáo chỉ có ở Nam Bộ với hàng trăm ghe thuyền. Tham quan vườn trái cây xum xuê, làng nghề bánh tráng, kẹo dừa. Hành hương Châu Đốc – miếu Bà Chúa Xứ Núi Sam linh thiêng, chùa Phước Điền cổ kính. Ngắm bình minh trên sông Hậu và cảnh làng quê bình yên. Thưởng thức ẩm thực miền Tây: bún cá, lẩu mắm, bánh tét lá cẩm và trái cây nhiệt đới.' WHERE TourID = 83;

UPDATE tour SET Description = 'Tour Hàn Quốc cao cấp 5 ngày 4 đêm với lịch trình signature đặc biệt. Seoul – thủ đô K-pop với cung điện Gyeongbokgung, Namsan Tower ngắm thành phố về đêm, khu Gangnam thời thượng, Hongdae sôi động. Đảo Nami – hòn đảo huyền thoại với đường cây lá phong đỏ rực mùa thu, bối cảnh phim Winter Sonata kinh điển. Trải nghiệm làm kimchi, thưởng thức BBQ Hàn Quốc và samgyeopsal chuẩn vị. Mua sắm mỹ phẩm K-beauty và thời trang tại Myeongdong. Resort 5 sao với view thành phố tuyệt đẹp.' WHERE TourID = 84;

UPDATE tour SET Description = 'Tour Nhật Bản premium 5 ngày 4 đêm khám phá Tokyo và Núi Phú Sĩ (Mt. Fuji) theo tiêu chuẩn cao cấp. Trải nghiệm Tokyo sôi động: Shibuya crossing đông đúc nhất thế giới, Harajuku phong cách, Akihabara thiên đường anime và công nghệ, chùa Senso-ji linh thiêng tại Asakusa. Ngắm Núi Phú Sĩ tuyết phủ từ hồ Kawaguchiko thơ mộng, trải nghiệm tắm onsen truyền thống. Thưởng thức ẩm thực Nhật cao cấp: sushi Tsukiji, ramen chuẩn vị, sake và wagyu bò Kobe. Khách sạn 5 sao trung tâm Tokyo.' WHERE TourID = 85;

UPDATE tour SET Description = 'Hành trình lãng mạn châu Âu 7 ngày 6 đêm qua Paris và Thụy Sĩ. Paris – kinh đô ánh sáng với Tháp Eiffel biểu tượng, bảo tàng Louvre – Mona Lisa, cung điện Versailles xa hoa, dạo thuyền sông Seine. Thụy Sĩ – đất nước đồng hồ với cảnh quan Alps tuyết trắng hùng vĩ, hồ Geneva trong xanh, thành phố Lucerne cổ kính với Cầu Kapellbrücke, Interlaken – trời ơi đẹp! Trải nghiệm tàu hỏa núi cao Jungfrau – nóc nhà châu Âu, thưởng thức chocolate và pho mát Thụy Sĩ chính hiệu.' WHERE TourID = 86;

UPDATE tour SET Description = 'Khám phá hai thành phố nổi bật nhất Australia trong 6 ngày 5 đêm. Sydney – thành phố biểu tượng với Nhà hát Opera Sydney, Cầu Cảng Harbour Bridge, bãi biển Bondi surf culture, Royal Botanic Garden. Dãy núi Blue Mountains huyền bí với Three Sisters và Jenolan Caves. Melbourne – thành phố sống động nhất Australia với làn đường nghệ thuật graffiti, chợ Queen Victoria, cà phê culture nổi tiếng thế giới, đội bóng AFL sôi nổi. Trải nghiệm wildlife Úc tại Phillip Island ngắm chim cánh cụt, ôm koala tại sở thú.' WHERE TourID = 87;
